version: '2'

networks:
  nat:
    external: true
  internal:
    external: false

services:

# Debug and SQL management only
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 9090:8080 # front:back

    reverse-proxy:
        env_file:
          - .env
        image: traefik:v1.7.19-alpine
        command:
          - "--defaultentrypoints=http,https"
          - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
          - "--entrypoints=Name:https Address::443 Compress:true TLS"
          - "--retry"
          - "--api"
          - "--docker"
          - "--docker.domain=docker.localhost"
          - "--docker.exposedbydefault=false"
          - "--loglevel=DEBUG"
          - "--acme=true"
          - "--acme.acmelogging=true"
          - "--acme.storage=/traefik/acme.json"
          - "--acme.entryPoint=https"
          - "--acme.httpchallenge"
          - "--acme.httpchallenge.entryPoint=http"
          - "--acme.onHostRule=true"
          - "--acme.email=matej@keyguru.eu"
          - "--acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
          - "--acme.domains=zentour.net,www.zentour.net"

    db:
      networks:
        - internal
      env_file:
        - .env
      image: mariadb:10
      container_name: mariadb
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    web-server:
      networks:
        - internal
        - nat
      env_file:
        - .env
      image: nginx:alpine
      restart: always
      container_name: frontend
      volumes:
        - ./www:/var/www/html
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
        - ./log/nginx/:/var/log/nginx/
        - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${WEB_PORT}:80"
        #- "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=web"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:zentour.net"
      #- "traefik.frontend.headers.forceSTSHeader=true"
      #- "traefik.frontend.headers.STSSeconds=315360000"
      #- "traefik.frontend.headers.STSIncludeSubdomains=true"
      #- "traefik.frontend.headers.STSPreload=true"

    wordpress-php-fpm:
      networks:
        - internal
        - nat
      env_file:
        - .env
      build:  conf/php-fpm
      restart: always
      container_name: php-fpm
      volumes:
        - ./www:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./data/wordpress/phpinfo.php:/var/www/html/phpinfo.php
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf