version: '3.3'

networks:
  nat:
    external: true
  internal:
    external: false

services:

# Debug and SQL management only
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 9090:8080 # front:back

    # traefik:
    #   env_file:
    #     - .env
    #   image: traefik:latest
    #   restart: unless-stopped
    #   ports:
    #     - "80:80"   # The HTTP port, should be 80 outside (does not collide on empty box)
    #     - "443:443"  # The HTTPS port, ditto.
    #     - "8080:8080" # Traefik port
    #     # - "8888:8888" # Optionally other port (e.g. Adminr)
    #   volumes:
    #     - ./traefik.yml:/etc/traefik/traefik.yml
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ./cert:/cert
    #     - ./traefik:/traefik
    #   labels:
    #     - "traefik.enable=true"
    #     - "traefik.http.routers.traefik.entrypoints=https"
    #     - "traefik.http.routers.traefik.rule=Host(`traefik.zentour.net`)"
    #     - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
    #     - "traefik.http.routers.traefik.middlewares=traefik-auth"
    #     - "traefik.http.routers.traefik.service=api@internal"
    #     - "traefik.http.routers.traefik.tls.certresolver=revolver"

    db:
      networks:
        - internal
      env_file:
        - .env
      image: mariadb:10
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}"

    wordpress:
        depends_on:
          - db
        networks:
          - nat
        image: wordpress:7.2-fpm-alpine
        ports:
          - "8000:80"
        restart: always
        env_file:
          - .env
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: ${MYSQL_USER}
          WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
          WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        volumes:
          - ./www:/var/www/html
          - ./data/wordpress/wp-content:/var/www/html/wp-content
          - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./log/nginx/:/var/log/nginx/
          - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "${WEB_PORT}:80"