version: '2'

networks:
  nat:
    external: true
  internal:
    external: false

services:

# Debug and SQL management only
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 9090:8080 # front:back

    traefik:
      env_file:
        - .env
      image: traefik:latest
      restart: unless-stopped
      ports:
        - "80:80"   # The HTTP port, should be 80 outside (does not collide on empty box)
        - "443:443"  # The HTTPS port, ditto.
        - "8080:8080" # Traefik port
        # - "8888:8888" # Optionally other port (e.g. Adminr)
      volumes:
        - ./traefik.yml:/etc/traefik/traefik.yml
        - /var/run/docker.sock:/var/run/docker.sock
        - ./cert:/cert
        - ./traefik:/traefik
      labels:
        - "traefik.port=8080"
        - "traefik.backend=traefik"
        - "traefik.frontend.auth.basic.users=traefik:$$apr1$$JVrTyD7r$DwX82aghrfYFJXh.kFfbU."
        - "traefik.frontend.rule=Host:traefik.zentour.net"

    db:
      networks:
        - internal
      env_file:
        - .env
      image: mariadb:10
      container_name: mariadb
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    web-server:
      networks:
        - internal
        - nat
      env_file:
        - .env
      image: nginx:alpine
      restart: always
      container_name: frontend
      volumes:
        - ./www:/var/www/html
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
        - ./log/nginx/:/var/log/nginx/
        - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${WEB_PORT}:80"
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=web"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:www.zentour.net"

    wordpress-php-fpm:
      networks:
        - internal
        - nat
      env_file:
        - .env
      build:  conf/php-fpm
      restart: always
      container_name: php-fpm
      volumes:
        - ./www:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./data/wordpress/phpinfo.php:/var/www/html/phpinfo.php
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf