version: '2'

networks:
  core-infra:
    external: true
  internal:
    external: false

services:

# Debug and SQL management only
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 9090:8080 # front:back

    proxy:
      image: nginx:alpine
      networks:
        - internal
        - core-infra
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./conf/proxy/nginx.conf:/etc/nginx/nginx.conf
        - ./log/proxy/:/var/log/nginx/
        - ./cert:/etc/nginx/ssl
        - ./conf/proxy/sites/default.conf:/etc/nginx/conf.d/default.conf

    mariadb:
      networks:
        - internal
      image: mariadb:10
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    frontend:
      networks:
        - core-infra
        - internal
      image: nginx:alpine
      restart: always
      volumes:
        - ./web:/var/www/html
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/nginx/cloudflare.conf:/etc/nginx/cloudflare.conf
        - ./log/nginx/:/var/log/nginx/
        - ./conf/nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        - run_vol:/var/run
      ports:
        - 8080:80

    php-fpm:
      networks:
        - core-infra
        - internal
      build:  conf/php-fpm
      restart: always
      ports: 
        - 9000
      volumes:
        - ./web:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./data/wordpress/phpinfo.php:/var/www/html/phpinfo.php
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs