version: '2'

networks:
  nat:
    external: true
  internal:
    external: false

services:

# Debug and SQL management only
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - 9090:8080 # front:back

    reverse-proxy:
        env_file:
          - .env
        image: traefik:v1.7.12-alpine
        command:
          - "--defaultentrypoints=http,https"
          - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
          - "--entrypoints=Name:https Address::443 Compress:true TLS"
          - "--retry"
          - "--api"
          - "--docker"
          - "--docker.domain=docker.localhost"
          - "--docker.exposedbydefault=false"
          - "--loglevel=DEBUG"
          - "--acme=true"
          - "--acme.acmelogging=true"
          - "--acme.storage=/traefik/acme.json"
          - "--acme.entryPoint=https"
          - "--acme.httpchallenge"
          - "--acme.httpchallenge.entryPoint=http"
          - "--acme.onHostRule=true"
          - "--acme.email=matej@keyguru.eu"
          - "--acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
          - "--acme.domains=zentour.net,traefik.zentour.net,www.zentour.net,wordpress.zentour.net"
        restart: unless-stopped
        ports:
          - "80:80"   # The HTTP port, should be 80 outside (does not collide on empty box)
          - "443:443"  # The HTTPS port, ditto.
          - "8080:8080" # Traefik port
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik:/traefik
        labels:
          - "traefik.port=8080"
          - "traefik.backend=traefik"
          #- "traefik.frontend.auth.basic.users=traefik:$$apr1$$JVrTyD7r$DwX82aghrfYFJXh.kFfbU."
          - "traefik.frontend.rule=Host:traefik.zentour.net"

    mariadb:
      networks:
        - internal
      env_file:
        - .env
      image: mariadb:10
      restart: always
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf/mariadb/my.cnf:/etc/mysql/conf.d/settings.cnf
        - ./conf/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    php-fpm:
      networks:
        - internal
        - nat
      env_file:
        - .env
      build: conf/php-fpm
      restart: always
      ports: 
        - "9000:9000"
      volumes:
        - ./www:/var/www/html
        - ./data/wordpress/wp-config.php:/var/www/html/wp-config.php
        - ./data/wordpress/wp-content:/var/www/html/wp-content
        - ./data/wordpress/phpinfo.php:/var/www/html/phpinfo.php
        - ./conf/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
        - ./conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.backend=web
        - traefik.frontend.rule=Host:www.zentour.net
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.headers.SSLRedirect=false